### ISSUE TITLE
Error : java.lang.IllegalStateException: Configuration error: found multiple declarations

### ISSUE THREAD

**Issue by ICU222** [ICU222/Project_room_escape_backend#2]
테스트 컨트롤러를 작성하던 도중 에러가 발생하였습니다. 

![t1](https://user-images.githubusercontent.com/29039922/149742391-26b1c29a-e698-464e-b8b0-10c722ba61d3.JPG)

해당 에러 내용은 다음과 같습니다. 

java.lang.IllegalStateException: Configuration error: found multiple declarations of@BootstrapWith for test class [icu222.roomescape.web.RoomescapeApplicationTests]: 

[@org.springframework.test.context.BootstrapWith(value=org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTestContextBootstrapper), 

@org.springframework.test.context.BootstrapWith(value=org.springframework.boot.test.context.SpringBootTestContextBootstrapper)]

하지만 import한 내용을 보면 겹치는 것이 없을음 알 수 있습니다. 
무엇이 문제일까요?

**Comment by okhee** [comment]
아마 Test Class 위에 작성한 annotation들 중 `@SpringBootTest`, `@WebMvcTest`를 중복으로 적어서 발생한 문제로 보입니다.
`@SpringBootTest`와 `@WebMvcTest`의 차이점, 사용법 등을 간략하게 보면 좋을 것 같습니다~!
https://goddaehee.tistory.com/212

**Comment by ICU222** [comment]
감사합니다. 덕분에 에러를 해결하였습니다. 
![omg](https://user-images.githubusercontent.com/29039922/149881987-2e550991-2309-4d51-8225-7622e3f4eff7.JPG)

왜 저 두 annotation을 중복으로 썼나 했더니,
![a1](https://user-images.githubusercontent.com/29039922/149882480-e2650577-7a86-47b3-b9e0-9e99bfd79b11.JPG)

Springboot initializer를 이용하여 만든 패키지의 test폴더에 이미 
org.springframework.boot.test.context.SpringBootTest가 import되어 있었고,


추가로 책에 있는대로

![a2](https://user-images.githubusercontent.com/29039922/149882572-a667f0fe-90ae-452f-83a1-eadabcadd206.JPG)

org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest를 import하여 
중복이 발생하였습니다.

저 두 패키지가 서로 중복이 될 것이라고는 생각을 못 하였습니다....
